# Generated by Django 3.2.3 on 2021-06-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activité', models.CharField(max_length=500)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
