# Generated by Django 3.2.3 on 2021-06-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cache',
            old_name='value',
            new_name='Competitivité',
        ),
    ]
