# Generated by Django 3.2.3 on 2021-06-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_value_cache_competitivité'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSite', models.CharField(max_length=500)),
                ('NoteGlobal', models.IntegerField()),
                ('Note_meta', models.IntegerField()),
                ('Note_page_quality', models.IntegerField()),
                ('Note_page_structure', models.IntegerField()),
                ('Note_link_structure', models.IntegerField()),
                ('Note_Server', models.IntegerField()),
                ('Note_Social', models.IntegerField()),
            ],
        ),
    ]
